# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
 
  UiPath:
    # The type of runner that the job will run on
    runs-on: windows-2016
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Download CLI
        run: |
          echo Hello, world!
          Install-Package UiPath.CLI -Version 1.0.7906.17381 -Source https://www.myget.org/F/uipath-dev/api/v3/index.json
          

      # Runs a set of commands using the runners shell
      - name: Package project
        run: |
          echo Packaging project 
          
          
       # Runs a set of commands using the runners shell
      - name: Run Tests
        run: |
          echo Running Tests
         
          
       # Runs a set of commands using the runners shell
      - name: Deploy project
        run: |
          echo Deploying package
          
